sudo: false
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
  - bundle exec rspec --color --format progress
